name: gun_club
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ^3.3.4

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^6.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  json_annotation: ^4.7.0
  package_info_plus: ^2.0.0
  supabase_flutter: ^1.0.0-dev.9

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
