name: gun_club
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ^3.3.4

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.2
  riverpod_annotation: ^1.1.1
  supabase_flutter: ^1.3.1
  intl: ^0.18.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
